/**
 * Xbox Dashboard - Recompiled Entry Point
 *
 * First-ever native PC port of the original Xbox Dashboard (build 3944).
 * Uses the xboxrecomp static recompilation toolkit.
 *
 * XBE Details (from xbe_parser):
 *   Title:       Xbox Dashboard
 *   Build:       3944 (v1.0)
 *   XBE Size:    1,394,036 bytes
 *   Entry point: TBD (Phase 1)
 *   Sections:    TBD
 *   Kernel imports: TBD
 */

#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* xboxrecomp runtime libraries */
#include "kernel/kernel.h"
#include "kernel/xbox_memory_layout.h"
#include "d3d/d3d8_xbox.h"
#include "audio/dsound_xbox.h"
#include "input/xinput_xbox.h"

/* ── Global register state (defined in xbox_memory_layout.c) ── */

extern uint32_t g_eax, g_ecx, g_edx, g_esp;
extern uint32_t g_ebx, g_esi, g_edi;
extern uint32_t g_seh_ebp;
extern ptrdiff_t g_xbox_mem_offset;

/* ── XBE Constants (TODO: update after Phase 1 XBE analysis) ── */

#define DASHBOARD_ENTRY_POINT   0x00052A81
#define DASHBOARD_XBE_PATH      "game\\xboxdash.xbe"
#define DASHBOARD_GAME_DIR      "game"

/* ── Forward declarations ──────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size);

/* Recompiled entry point (generated by recomp pipeline) */
extern void xbe_entry_point(void);

/* ── XIP crash recovery ────────────────────────────────────── */

/* When set to 1, the VEH handler will skip faulting MEM32 reads
 * by setting the destination register to 0 and resuming. This allows
 * XIP loading to continue past unrebased pointers. */
volatile int g_xip_crash_skip = 0;
static int g_xip_crash_count = 0;

/* ── VEH crash handler ─────────────────────────────────────── */

static LONG CALLBACK veh_handler(PEXCEPTION_POINTERS ep)
{
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_ACCESS_VIOLATION) {
        uintptr_t fault_addr = ep->ExceptionRecord->ExceptionInformation[1];
        int is_read = (ep->ExceptionRecord->ExceptionInformation[0] == 0);

        /* GPU register probe at 0xFD000000 range - return zero */
        if (fault_addr >= 0xFD000000 && fault_addr < 0xFE000000) {
            return EXCEPTION_CONTINUE_SEARCH;
        }

        /* During XIP loading: recover from out-of-range reads by returning 0.
         * The faulting instruction is a MOV from [addr] - we skip it by
         * advancing RIP past the instruction and zeroing the destination. */
        if (is_read && g_xip_crash_skip) {
            uint32_t xbox_va = (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset);
            if (xbox_va >= 0x04000000) {
                g_xip_crash_count++;
                if (g_xip_crash_count <= 5) {
                    fprintf(stderr, "[XIP RECOVER] #%d: skip read at Xbox VA 0x%08X (RIP=0x%llX)\n",
                        g_xip_crash_count, xbox_va,
                        (unsigned long long)ep->ContextRecord->Rip);
                    fflush(stderr);
                }
                /* Zero the global registers and try to continue.
                 * The faulting access is via MEM32() which reads a global;
                 * we can't easily skip x64 instructions, so just zero the
                 * target. MEM32 expands to *(volatile uint32_t*)XBOX_PTR(addr).
                 * Map the fault address to valid memory and write 0 there. */
                /* Allocate a zero page for bad reads to land on */
                static uint8_t s_zero_page[4096] = {0};
                /* Redirect: patch the fault address to point to our zero page */
                /* Actually, just set Rax to 0 (most reads go into eax/ecx/edx/etc)
                 * and skip the faulting instruction. Instruction length heuristic: */
                unsigned char *rip = (unsigned char *)ep->ContextRecord->Rip;
                int insn_len = 0;
                /* Common x64 MOV patterns: REX.W prefix (0x48-0x4F) + opcode + modrm + sib + disp */
                if (rip[0] >= 0x48 && rip[0] <= 0x4F) insn_len++; /* REX prefix */
                if (rip[insn_len] == 0x8B || rip[insn_len] == 0x0F || rip[insn_len] == 0x89 ||
                    rip[insn_len] == 0x3B || rip[insn_len] == 0x39 || rip[insn_len] == 0x85) {
                    /* MOV r, [m] / CMP etc. - scan for instruction end */
                    /* Simple heuristic: find next instruction by scanning up to 15 bytes */
                    insn_len = 3; /* minimum: opcode + modrm + 1 */
                    unsigned char modrm = rip[insn_len - 1];
                    int mod = (modrm >> 6) & 3;
                    int rm = modrm & 7;
                    if (rm == 4) insn_len++; /* SIB byte */
                    if (mod == 0 && rm == 5) insn_len += 4; /* RIP-relative */
                    else if (mod == 1) insn_len += 1; /* disp8 */
                    else if (mod == 2) insn_len += 4; /* disp32 */
                }
                if (insn_len < 2) insn_len = 7; /* fallback: assume 7-byte instruction */
                ep->ContextRecord->Rax = 0;
                ep->ContextRecord->Rip += insn_len;
                return EXCEPTION_CONTINUE_EXECUTION;
            }
        }

        fprintf(stderr, "[CRASH] Access violation at RIP=0x%llX, fault addr=0x%llX (%s)\n",
            (unsigned long long)ep->ContextRecord->Rip,
            (unsigned long long)fault_addr,
            ep->ExceptionRecord->ExceptionInformation[0] ? "write" : "read");
        fprintf(stderr, "  Xbox regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n",
            g_eax, g_ecx, g_edx, g_esp);
        fprintf(stderr, "  Xbox regs: ebx=0x%08X esi=0x%08X edi=0x%08X\n",
            g_ebx, g_esi, g_edi);
        fprintf(stderr, "  Xbox VA of fault: 0x%08X\n",
            (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset));

        /* Print native stack return addresses for debugging */
        {
            uintptr_t *sp = (uintptr_t *)ep->ContextRecord->Rsp;
            fprintf(stderr, "  Native stack (first 8 return addrs):\n");
            for (int i = 0; i < 64 && sp[i]; i++) {
                if (sp[i] >= 0x140000000ULL && sp[i] < 0x150000000ULL) {
                    fprintf(stderr, "    [%d] 0x%llX\n", i, (unsigned long long)sp[i]);
                }
            }
        }
        fflush(stderr);
    }

    return EXCEPTION_CONTINUE_SEARCH;
}

/* ── Dashboard Window ──────────────────────────────────────── */

static HWND g_dashboard_hwnd = NULL;
IDirect3DDevice8 *g_d3d_device = NULL; /* non-static: accessed by D3D bridges */

static LRESULT CALLBACK dashboard_wndproc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
    switch (msg) {
    case WM_CLOSE:
        PostQuitMessage(0);
        return 0;
    case WM_DESTROY:
        PostQuitMessage(0);
        return 0;
    }
    return DefWindowProcA(hWnd, msg, wParam, lParam);
}

static HWND create_dashboard_window(HINSTANCE hInstance)
{
    WNDCLASSEXA wc = {0};
    wc.cbSize = sizeof(wc);
    wc.style = CS_HREDRAW | CS_VREDRAW;
    wc.lpfnWndProc = dashboard_wndproc;
    wc.hInstance = hInstance;
    wc.hCursor = LoadCursor(NULL, IDC_ARROW);
    wc.hbrBackground = (HBRUSH)GetStockObject(BLACK_BRUSH);
    wc.lpszClassName = "XboxDashboard";
    RegisterClassExA(&wc);

    /* Xbox dashboard renders at 640x480 */
    RECT rc = {0, 0, 640, 480};
    AdjustWindowRect(&rc, WS_OVERLAPPEDWINDOW, FALSE);

    HWND hwnd = CreateWindowExA(0, "XboxDashboard", "Xbox Dashboard - Recompiled",
                                WS_OVERLAPPEDWINDOW,
                                CW_USEDEFAULT, CW_USEDEFAULT,
                                rc.right - rc.left, rc.bottom - rc.top,
                                NULL, NULL, hInstance, NULL);
    if (hwnd) {
        ShowWindow(hwnd, SW_SHOW);
        UpdateWindow(hwnd);
    }
    return hwnd;
}

static BOOL init_d3d_device(HWND hwnd)
{
    IDirect3D8 *d3d = xbox_Direct3DCreate8(0);
    if (!d3d) {
        fprintf(stderr, "[D3D8] Failed to create IDirect3D8\n");
        return FALSE;
    }

    D3DPRESENT_PARAMETERS pp = {0};
    pp.BackBufferWidth = 640;
    pp.BackBufferHeight = 480;
    pp.BackBufferFormat = 0x12; /* D3DFMT_A8R8G8B8 */
    pp.BackBufferCount = 1;
    pp.SwapEffect = 1; /* D3DSWAPEFFECT_DISCARD */
    pp.hDeviceWindow = hwnd;
    pp.Windowed = TRUE;
    pp.EnableAutoDepthStencil = TRUE;
    pp.AutoDepthStencilFormat = 0x2A; /* D3DFMT_D24S8 */

    HRESULT hr = d3d->lpVtbl->CreateDevice(d3d, 0, 1, hwnd, 0x40, &pp, &g_d3d_device);
    if (FAILED(hr)) {
        fprintf(stderr, "[D3D8] CreateDevice failed: 0x%08lX\n", hr);
        return FALSE;
    }

    fprintf(stderr, "[D3D8] Device created successfully: %ux%u\n", pp.BackBufferWidth, pp.BackBufferHeight);
    return TRUE;
}

/* ── Per-frame D3D pump (called from main loop) ──────────── */

/* Called before tick+render: pump messages */
void dashboard_present_frame(void)
{
    /* Pump Windows messages */
    MSG msg;
    while (PeekMessageA(&msg, NULL, 0, 0, PM_REMOVE)) {
        if (msg.message == WM_QUIT) ExitProcess(0);
        TranslateMessage(&msg);
        DispatchMessageA(&msg);
    }
}

/* Called before render: clear + BeginScene */
void dashboard_begin_frame(void)
{
    if (!g_d3d_device) return;

    /* Clear to Xbox dark green */
    g_d3d_device->lpVtbl->Clear(g_d3d_device, 0, NULL, 1 | 2,
                                 0xFF003300, 1.0f, 0);
    g_d3d_device->lpVtbl->BeginScene(g_d3d_device);
}

/* Called after render: EndScene + Present */
void dashboard_end_frame(void)
{
    if (!g_d3d_device) return;

    g_d3d_device->lpVtbl->EndScene(g_d3d_device);
    g_d3d_device->lpVtbl->Present(g_d3d_device, NULL, NULL, NULL, NULL);

    /* Throttle D3D bridge logging after initial frames */
    extern void d3d_bridge_new_frame(void);
    d3d_bridge_new_frame();
}

/* ── WinMain ───────────────────────────────────────────────── */

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
                   LPSTR lpCmdLine, int nCmdShow)
{
    void *xbe_data = NULL;
    size_t xbe_size = 0;

    (void)hInstance;
    (void)hPrevInstance;
    (void)lpCmdLine;
    (void)nCmdShow;

    /* Unbuffered output for immediate visibility */
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);

    printf("=== Xbox Dashboard - Static Recompilation ===\n");
    printf("Build 3944 (v1.0) - First-ever native PC port\n\n");
    printf("Loading XBE...\n");

    /* Install VEH handler */
    AddVectoredExceptionHandler(1, veh_handler);

    /* Step 1: Load XBE */
    if (!load_xbe(DASHBOARD_XBE_PATH, &xbe_data, &xbe_size)) {
        MessageBoxA(NULL, "Failed to load xboxdash.xbe.\n"
                    "Place the dashboard files in the 'game' subdirectory.",
                    "Xbox Dashboard Recomp", MB_ICONERROR);
        return 1;
    }
    printf("XBE loaded: %zu bytes\n", xbe_size);

    /* Step 2: Initialize Xbox memory layout */
    printf("Initializing Xbox memory layout...\n");
    if (!xbox_MemoryLayoutInit(xbe_data, xbe_size)) {
        MessageBoxA(NULL, "Failed to initialize Xbox memory layout.\n"
                    "The required virtual address range may be unavailable.",
                    "Xbox Dashboard Recomp", MB_ICONERROR);
        free(xbe_data);
        return 1;
    }

    g_xbox_mem_offset = xbox_GetMemoryOffset();
    printf("Xbox memory mapped. Offset: 0x%llX\n", (unsigned long long)g_xbox_mem_offset);

    /* Step 3: Initialize Xbox kernel */
    printf("Initializing Xbox kernel replacement...\n");
    xbox_kernel_init();

    /* Step 3a: Initialize NV2A GPU emulation.
     * The D3D section code reads/writes NV2A registers at 0xFD000000.
     * The MMIO hook uses a VEH to intercept these and route to software NV2A. */
    {
        extern void nv2a_hook_init(ptrdiff_t xbox_mem_offset);
        nv2a_hook_init(g_xbox_mem_offset);
    }

    /* Step 3b: Set game directory for file I/O
     * The dashboard accesses C:\ for its own files (XIP archives, fonts, audio)
     * and D:\xodash\ for the online dashboard. We map both to our game/ dir. */
    {
        extern void xbox_path_init(const char* game_dir, const char* save_dir);
        /* Dashboard: C:\ maps to game/, T:/U:/Z: also map to game/ (all same partition) */
        xbox_path_init(DASHBOARD_GAME_DIR, DASHBOARD_GAME_DIR);
    }

    /* Step 4: Initialize kernel bridge */
    printf("Initializing kernel bridge...\n");
    xbox_kernel_bridge_init();

    /* Step 4b: Pre-initialize CRT thread index.
     * The CRT uses MEM32(0x12D798) as the TLS slot index for per-thread
     * data (__getptd). In BSS it should be 0 but gets corrupted.
     * Set it to 0 to ensure single-threaded CRT works correctly. */
    {
        volatile uint32_t *tls_idx = (volatile uint32_t *)((uintptr_t)0x12D798 + g_xbox_mem_offset);
        *tls_idx = 0;
    }

    /* Step 4c: Pre-initialize CRT lock table.
     * The Xbox CRT has a table of critical section pointers at 0x113318,
     * with 8 bytes per entry (pointer + flags), 36 entries (locks 0-35).
     * Lock #10 is the "lock-table lock" used by _mtinitlocknum. If it's
     * not pre-initialized, _lock() infinitely recurses trying to init it.
     * Since we're single-threaded (RtlEnter/LeaveCriticalSection are no-ops),
     * we just write dummy non-zero values so the init check passes. */
    {
        volatile uint32_t *lock_table = (volatile uint32_t *)((uintptr_t)0x113318 + g_xbox_mem_offset);
        for (int i = 0; i < 36; i++) {
            lock_table[i * 2] = 0xDEAD0000 + i;  /* fake CS pointer (non-zero) */
            /* lock_table[i*2 + 1] stays 0 (flags) */
        }
    }

    /* Step 5: Initialize stack */
    g_esp = XBOX_STACK_TOP;

    /* Step 5b: Create the dashboard window and D3D device */
    printf("Creating dashboard window...\n");
    g_dashboard_hwnd = create_dashboard_window(hInstance);
    if (!g_dashboard_hwnd) {
        MessageBoxA(NULL, "Failed to create dashboard window.",
                    "Xbox Dashboard Recomp", MB_ICONERROR);
        return 1;
    }

    printf("Initializing D3D8 device...\n");
    if (!init_d3d_device(g_dashboard_hwnd)) {
        MessageBoxA(NULL, "Failed to create D3D8 device.\n"
                    "Make sure your GPU supports D3D11 Feature Level 10.0.",
                    "Xbox Dashboard Recomp", MB_ICONERROR);
        return 1;
    }

    printf("\n=== Initialization complete ===\n");
    printf("Entry point: 0x%08X\n", DASHBOARD_ENTRY_POINT);
    printf("ESP: 0x%08X\n", g_esp);

    /* Step 6: Call the recompiled entry point */
    printf("\nStarting dashboard...\n");
    fflush(stdout);

    xbe_entry_point();

    printf("\nDashboard returned. Cleaning up...\n");

    /* Cleanup */
    xbox_kernel_shutdown();
    xbox_MemoryLayoutShutdown();
    free(xbe_data);

    return 0;
}

/* ── XBE Loading ───────────────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Cannot open XBE: %s\n", path);
        return FALSE;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size <= 0) {
        fclose(f);
        return FALSE;
    }

    void *data = malloc((size_t)size);
    if (!data) {
        fclose(f);
        return FALSE;
    }

    if (fread(data, 1, (size_t)size, f) != (size_t)size) {
        free(data);
        fclose(f);
        return FALSE;
    }

    fclose(f);
    *out_data = data;
    *out_size = (size_t)size;
    return TRUE;
}

/* Console entry point (for debugging) */
int main(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    return WinMain(GetModuleHandle(NULL), NULL, GetCommandLineA(), SW_SHOW);
}
